### ISSUE TITLE
"No CachingProviders have been configured" error

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/draft-guide-sessions#139]
Ran into this with the current version available through openliberty.io i.e. the current code in "prod".

@GraceJansen @mgrygles

---

[INFO] [ERROR   ] SESN0309E: The jCacheVendorLib session cache library is empty. Verify that the server configuration contains a valid httpSessionCache configuration. See the sample configuration. 
[INFO] 
[INFO]     <httpSessionCache libraryRef="JCacheLib"/>
[INFO] 
[INFO]    <library id="JCacheLib">
[INFO]         <file name="${shared.resource.dir}/jcache/JCacheProvider.jar"/>
[INFO]     </library>
[INFO] 
[INFO] [ERROR   ] SESN0307E: An exception occurred when initializing the cache. The exception is: javax.cache.CacheException: No CachingProviders have been configured
[INFO] 	at javax.cache.Caching$CachingProviderRegistry.getCachingProvider(Caching.java:391)
[INFO] 	at javax.cache.Caching.getCachingProvider(Caching.java:169)
[INFO] 	at com.ibm.ws.session.store.cache.CacheStoreService.lambda$activateLazily$0(CacheStoreService.java:211)
[INFO] 	at [internal classes]
[INFO] .
[INFO] [ERROR   ] SRVE8059E: An unexpected exception occurred when trying to retrieve the session context
[INFO] Internal Server Error
[INFO] [AUDIT   ] CWWKZ0003I: The application guide-sessions updated in 0.107 seconds.

**Comment by yeekangc** [comment]
This doesn't appear the dependent library was present/downloaded?
